/* Generated by           cobc 3.1.2.0 */
/* Generated from         DatabaseDemo.cob */
/* Generated at           Sep 08 2026 16:47:02 */
/* GnuCOBOL build date    Sep 14 2021 19:23:38 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -free DatabaseDemo.cob */

/* Program local variables for 'DatabaseDemo' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;


/* Call pointers */
static cob_call_union	call_cob_sqlite_open;
static cob_call_union	call_cob_sqlite_exec;
static cob_call_union	call_cob_sqlite_prepare;
static cob_call_union	call_cob_sqlite_step;
static cob_call_union	call_cob_sqlite_get_int;
static cob_call_union	call_cob_sqlite_get_text;
static cob_call_union	call_cob_sqlite_get_double;
static cob_call_union	call_cob_sqlite_finalize;
static cob_call_union	call_cob_sqlite_close;

/* Call parameters */
cob_field		*cob_procedure_params[4];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[4] __attribute__((aligned));	/* SQLITE-STATUS */
static cob_u8_t	b_12[8] __attribute__((aligned));	/* DB-HANDLE */
static cob_u8_t	b_13[8] __attribute__((aligned));	/* STMT-HANDLE */
static cob_u8_t	b_14[512] __attribute__((aligned));	/* SQL-STATEMENT */
static cob_u8_t	b_15[52] __attribute__((aligned));	/* EMP-RECORD */
static cob_u8_t	b_21[11] __attribute__((aligned));	/* WS-TOTAL-SALARY */
static cob_u8_t	b_22[4] __attribute__((aligned));	/* WS-EMP-COUNT */
static cob_u8_t	b_23[9] __attribute__((aligned));	/* WS-AVG-SALARY */
static cob_u8_t	b_24[4] __attribute__((aligned));	/* DISP-EMP-ID */
static cob_u8_t	b_25[14] __attribute__((aligned));	/* DISP-SALARY */
static cob_u8_t	b_26[14] __attribute__((aligned));	/* DISP-TOTAL */
static cob_u8_t	b_27[14] __attribute__((aligned));	/* DISP-AVG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {4, b_8, &a_4};	/* SQLITE-STATUS */
static cob_field f_12	= {8, b_12, &a_3};	/* DB-HANDLE */
static cob_field f_13	= {8, b_13, &a_3};	/* STMT-HANDLE */
static cob_field f_14	= {512, b_14, &a_2};	/* SQL-STATEMENT */
static cob_field f_16	= {4, b_15, &a_4};	/* EMP-ID */
static cob_field f_17	= {20, b_15 + 4, &a_2};	/* EMP-NAME */
static cob_field f_18	= {15, b_15 + 24, &a_2};	/* EMP-DEPT */
static cob_field f_19	= {8, b_15 + 39, &a_7};	/* EMP-SALARY-DBL */
static cob_field f_20	= {5, b_15 + 47, &a_8};	/* EMP-SALARY-DEC */
static cob_field f_21	= {11, b_21, &a_10};	/* WS-TOTAL-SALARY */
static cob_field f_22	= {4, b_22, &a_9};	/* WS-EMP-COUNT */
static cob_field f_23	= {9, b_23, &a_13};	/* WS-AVG-SALARY */
static cob_field f_24	= {4, b_24, &a_11};	/* DISP-EMP-ID */
static cob_field f_25	= {14, b_25, &a_12};	/* DISP-SALARY */
static cob_field f_26	= {14, b_26, &a_12};	/* DISP-TOTAL */
static cob_field f_27	= {14, b_27, &a_12};	/* DISP-AVG */

/* End of fields */

