/* Generated by           cobc 3.1.2.0 */
/* Generated from         DatabaseDemo.cob */
/* Generated at           Sep 08 2026 16:47:02 */
/* GnuCOBOL build date    Sep 14 2021 19:23:38 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -free DatabaseDemo.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"DatabaseDemo.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 08 2026 16:47:02"
#define  COB_MODULE_DATE		20260908
#define  COB_MODULE_TIME		164702

/* Global variables */
#include "DatabaseDemo.c.h"

/* Function prototypes */

int		DatabaseDemo (void);
static int		DatabaseDemo_ (const int);
static void		DatabaseDemo_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'DatabaseDemo' */

/* ENTRY 'DatabaseDemo' */

int
DatabaseDemo ()
{
  return DatabaseDemo_ (0);
}

static int
DatabaseDemo_ (const int entry)
{
  /* Program local variables */
  #include "DatabaseDemo.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 42        : Entry     DatabaseDemo            : DatabaseDemo.cob */
  l_2:;

  /* Line: 43        : Paragraph 0000-MAIN               : DatabaseDemo.cob */

  /* Line: 44        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_1);

  /* Line: 45        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_2);

  /* Line: 46        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_1);

  /* Line: 48        : PERFORM            : DatabaseDemo.cob */
  /* PERFORM 1000-CONNECT-DB */
  frame_ptr++;
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_12;
  goto l_5;
  l_12:
  frame_ptr--;

  /* Line: 49        : PERFORM            : DatabaseDemo.cob */
  /* PERFORM 2000-SETUP-SCHEMA */
  frame_ptr++;
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_13;
  goto l_6;
  l_13:
  frame_ptr--;

  /* Line: 50        : PERFORM            : DatabaseDemo.cob */
  /* PERFORM 3000-INSERT-EMPLOYEES */
  frame_ptr++;
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_7;
  l_14:
  frame_ptr--;

  /* Line: 51        : PERFORM            : DatabaseDemo.cob */
  /* PERFORM 4000-QUERY-EMPLOYEES */
  frame_ptr++;
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_15;
  goto l_8;
  l_15:
  frame_ptr--;

  /* Line: 52        : PERFORM            : DatabaseDemo.cob */
  /* PERFORM 5000-CLEANUP */
  frame_ptr++;
  frame_ptr->perform_through = 11;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_11;
  l_16:
  frame_ptr--;

  /* Line: 54        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_1);

  /* Line: 55        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_3);

  /* Line: 56        : MOVE               : DatabaseDemo.cob */
  b_2 = 0;

  /* Line: 57        : STOP RUN           : DatabaseDemo.cob */
  cob_stop_run (b_2);

  /* Line: 59        : Paragraph 1000-CONNECT-DB         : DatabaseDemo.cob */
  l_5:;

  /* Line: 60        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_4);

  /* Line: 61        : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_5, &f_14);

  /* Line: 62        : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_14;
  cob_procedure_params[1] = &f_12;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_open.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_open.funcvoid = cob_resolve_cobol ("cob_sqlite_open", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_open.funcint) (b_14, b_12, b_8);

  /* Line: 67        : IF                 : DatabaseDemo.cob */
  if (!((int)cob_cmp_s32 (b_8, 0LL) == 0))
  {

    /* Line: 68        : DISPLAY            : DatabaseDemo.cob */
    cob_display (0, 1, 2, &c_6, &f_8);

    /* Line: 69        : STOP RUN           : DatabaseDemo.cob */
    cob_stop_run (b_2);
  }

  /* Line: 71        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_7);

  /* Line: 72        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_8);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 74        : Paragraph 2000-SETUP-SCHEMA       : DatabaseDemo.cob */
  l_6:;

  /* Line: 75        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_9);

  /* Line: 76        : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_10, &f_14);

  /* Line: 78        : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 83        : IF                 : DatabaseDemo.cob */
  if (!((int)cob_cmp_s32 (b_8, 0LL) == 0))
  {

    /* Line: 84        : DISPLAY            : DatabaseDemo.cob */
    cob_display (0, 1, 2, &c_11, &f_8);

    /* Line: 85        : STOP RUN           : DatabaseDemo.cob */
    cob_stop_run (b_2);
  }

  /* Line: 88        : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_12, &f_14);

  /* Line: 89        : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 93        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_13);

  /* Line: 94        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_8);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 96        : Paragraph 3000-INSERT-EMPLOYEES   : DatabaseDemo.cob */
  l_7:;

  /* Line: 97        : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_14);

  /* Line: 99        : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_15, &f_14);

  /* Line: 101       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 103       : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_16, &f_14);

  /* Line: 105       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 107       : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_17, &f_14);

  /* Line: 109       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 111       : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_18, &f_14);

  /* Line: 113       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_8;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_exec.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_exec.funcvoid = cob_resolve_cobol ("cob_sqlite_exec", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_cob_sqlite_exec.funcint) (b_12, b_14, b_8);

  /* Line: 115       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_19);

  /* Line: 116       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_8);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 118       : Paragraph 4000-QUERY-EMPLOYEES    : DatabaseDemo.cob */
  l_8:;

  /* Line: 119       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_20);

  /* Line: 120       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_21);

  /* Line: 121       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_22);

  /* Line: 122       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_21);

  /* Line: 124       : MOVE               : DatabaseDemo.cob */
  cob_move ((cob_field *)&c_23, &f_14);

  /* Line: 126       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_14;
  cob_procedure_params[2] = &f_13;
  cob_procedure_params[3] = &f_8;
  cob_glob_ptr->cob_call_params = 4;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_prepare.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_prepare.funcvoid = cob_resolve_cobol ("cob_sqlite_prepare", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *, void *))call_cob_sqlite_prepare.funcint) (b_12, b_14, b_13, b_8);

  /* Line: 132       : IF                 : DatabaseDemo.cob */
  if (!((int)cob_cmp_s32 (b_8, 0LL) == 0))
  {

    /* Line: 133       : DISPLAY            : DatabaseDemo.cob */
    cob_display (0, 1, 2, &c_24, &f_8);

    /* Line: 134       : EXIT PARAGRAPH     : DatabaseDemo.cob */
    goto l_9;
  }

  /* Line: 137       : PERFORM            : DatabaseDemo.cob */
  for (;;)
  {
    if (0)
      break;

    /* Line: 138       : CALL               : DatabaseDemo.cob */
    cob_procedure_params[0] = &f_13;
    cob_procedure_params[1] = &f_8;
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_cob_sqlite_step.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
    {
      call_cob_sqlite_step.funcvoid = cob_resolve_cobol ("cob_sqlite_step", 0, 1);
    }
    b_2 = ((int (*)(void *, void *))call_cob_sqlite_step.funcint) (b_13, b_8);

    /* Line: 142       : IF                 : DatabaseDemo.cob */
    if (((int)cob_cmp_s32 (b_8, 100LL) == 0))
    {

      /* Line: 144       : CALL               : DatabaseDemo.cob */
      cob_procedure_params[0] = &f_13;
      cob_procedure_params[1] = (cob_field *)&c_25;
      cob_procedure_params[2] = &f_16;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_cob_sqlite_get_int.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_cob_sqlite_get_int.funcvoid = cob_resolve_cobol ("cob_sqlite_get_int", 0, 1);
      }
      b_2 = ((int (*)(void *, cob_s32_t, void *))call_cob_sqlite_get_int.funcint) (b_13, (cob_s32_t)0LL, b_15);

      /* Line: 150       : CALL               : DatabaseDemo.cob */
      cob_procedure_params[0] = &f_13;
      cob_procedure_params[1] = (cob_field *)&c_26;
      cob_procedure_params[2] = &f_17;
      cob_procedure_params[3] = (cob_field *)&c_27;
      cob_glob_ptr->cob_call_params = 4;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_cob_sqlite_get_text.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_cob_sqlite_get_text.funcvoid = cob_resolve_cobol ("cob_sqlite_get_text", 0, 1);
      }
      b_2 = ((int (*)(void *, cob_s32_t, void *, cob_s32_t))call_cob_sqlite_get_text.funcint) (b_13, (cob_s32_t)1LL, b_15 + 4, (cob_s32_t)20LL);

      /* Line: 157       : CALL               : DatabaseDemo.cob */
      cob_procedure_params[0] = &f_13;
      cob_procedure_params[1] = (cob_field *)&c_28;
      cob_procedure_params[2] = &f_18;
      cob_procedure_params[3] = (cob_field *)&c_29;
      cob_glob_ptr->cob_call_params = 4;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_cob_sqlite_get_text.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_cob_sqlite_get_text.funcvoid = cob_resolve_cobol ("cob_sqlite_get_text", 0, 1);
      }
      b_2 = ((int (*)(void *, cob_s32_t, void *, cob_s32_t))call_cob_sqlite_get_text.funcint) (b_13, (cob_s32_t)2LL, b_15 + 24, (cob_s32_t)15LL);

      /* Line: 164       : CALL               : DatabaseDemo.cob */
      cob_procedure_params[0] = &f_13;
      cob_procedure_params[1] = (cob_field *)&c_30;
      cob_procedure_params[2] = &f_19;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_cob_sqlite_get_double.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
      {
        call_cob_sqlite_get_double.funcvoid = cob_resolve_cobol ("cob_sqlite_get_double", 0, 1);
      }
      b_2 = ((int (*)(void *, cob_s32_t, void *))call_cob_sqlite_get_double.funcint) (b_13, (cob_s32_t)3LL, b_15 + 39);

      /* Line: 169       : COMPUTE            : DatabaseDemo.cob */
      cob_decimal_set_field (d0, &f_19);
      cob_decimal_get_field (d0, &f_20, 1);

      /* Line: 170       : ADD                : DatabaseDemo.cob */
      cob_add_int (&f_22, 1, 0);

      /* Line: 171       : ADD                : DatabaseDemo.cob */
      cob_add (&f_21, &f_20, 0);

      /* Line: 173       : MOVE               : DatabaseDemo.cob */
      cob_move (&f_16, &f_24);

      /* Line: 174       : MOVE               : DatabaseDemo.cob */
      cob_move (&f_20, &f_25);

      /* Line: 175       : DISPLAY            : DatabaseDemo.cob */
      cob_display (0, 1, 7, &f_24, &c_31, &f_17, &c_31, &f_18, &c_31, &f_25);
    }
    else
    {
      /* ELSE */

      /* Line: 177       : EXIT PERFORM       : DatabaseDemo.cob */
      goto l_10;
    }
  }

  /* Implicit EXIT label */
  l_10:;

  /* Line: 181       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_13;
  cob_procedure_params[1] = &f_8;
  cob_glob_ptr->cob_call_params = 2;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_finalize.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_finalize.funcvoid = cob_resolve_cobol ("cob_sqlite_finalize", 0, 1);
  }
  b_2 = ((int (*)(void *, void *))call_cob_sqlite_finalize.funcint) (b_13, b_8);

  /* Line: 185       : IF                 : DatabaseDemo.cob */
  if (((int)cob_cmp_numdisp (b_22, 4, 0LL, 0) > 0))
  {

    /* Line: 186       : COMPUTE            : DatabaseDemo.cob */
    cob_decimal_set_field (d0, &f_21);
    cob_decimal_set_field (d1, &f_22);
    cob_decimal_div (d0, d1);
    cob_decimal_get_field (d0, &f_23, 0);
  }

  /* Line: 189       : MOVE               : DatabaseDemo.cob */
  cob_move (&f_21, &f_26);

  /* Line: 190       : MOVE               : DatabaseDemo.cob */
  cob_move (&f_23, &f_27);

  /* Line: 191       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_21);

  /* Line: 192       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 2, &c_32, &f_22);

  /* Line: 193       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 2, &c_33, &f_26);

  /* Line: 194       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 2, &c_34, &f_27);

  /* Line: 195       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_8);

  /* Implicit EXIT label */
  l_9:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 197       : Paragraph 5000-CLEANUP            : DatabaseDemo.cob */
  l_11:;

  /* Line: 198       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_35);

  /* Line: 199       : CALL               : DatabaseDemo.cob */
  cob_procedure_params[0] = &f_12;
  cob_procedure_params[1] = &f_8;
  cob_glob_ptr->cob_call_params = 2;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_cob_sqlite_close.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_cob_sqlite_close.funcvoid = cob_resolve_cobol ("cob_sqlite_close", 0, 1);
  }
  b_2 = ((int (*)(void *, void *))call_cob_sqlite_close.funcint) (b_12, b_8);

  /* Line: 202       : DISPLAY            : DatabaseDemo.cob */
  cob_display (0, 1, 1, &c_36);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  DatabaseDemo_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  cob_move ((cob_field *)&c_25, &f_8);
  (*(unsigned char **) (b_12)) = (cob_u8_ptr)NULL;
  (*(unsigned char **) (b_13)) = (cob_u8_ptr)NULL;
  memset (b_14, 32, 512);
  memset (b_15, 0, 4);
  memset (b_15 + 4, 32, 35);
  {double temp = 0.0; memcpy (b_15 + 39, (void *)&temp, sizeof(temp));}
  cob_set_packed_zero (&f_20);
  cob_move ((cob_field *)&c_25, &f_21);
  memset (b_22, 48, 4);
  cob_move ((cob_field *)&c_25, &f_23);
  cob_move (&cob_all_zero, &f_24);
  cob_move (&cob_all_zero, &f_25);
  cob_move (&cob_all_zero, &f_26);
  cob_move (&cob_all_zero, &f_27);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  call_cob_sqlite_close.funcvoid = NULL;
  call_cob_sqlite_finalize.funcvoid = NULL;
  call_cob_sqlite_get_double.funcvoid = NULL;
  call_cob_sqlite_get_text.funcvoid = NULL;
  call_cob_sqlite_get_int.funcvoid = NULL;
  call_cob_sqlite_step.funcvoid = NULL;
  call_cob_sqlite_prepare.funcvoid = NULL;
  call_cob_sqlite_exec.funcvoid = NULL;
  call_cob_sqlite_open.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'DatabaseDemo' */

/* Initialize module structure for DatabaseDemo */
static void DatabaseDemo_module_init (cob_module *module)
{
  module->module_name = "DatabaseDemo";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())DatabaseDemo;
  module->module_cancel.funcptr = (void *(*)())DatabaseDemo_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

