/* Generated by           cobc 3.1.2.0 */
/* Generated from         DatabaseDemo.cob */
/* Generated at           Sep 08 2026 16:47:02 */
/* GnuCOBOL build date    Sep 14 2021 19:23:38 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -free DatabaseDemo.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 3},
	{'9', 1},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'$', 3},
	{',', 1},
	{'$', 3},
	{',', 1},
	{'$', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x11,  17,   0, 0x0080, NULL};
static const cob_field_attr a_4 =	{0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_5 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_6 =	{0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_7 =	{0x14,  34,  17, 0x0201, NULL};
static const cob_field_attr a_8 =	{0x12,   9,   2, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_10 =	{0x10,  11,   2, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x24,   4,   0, 0x0000, p_1};
static const cob_field_attr a_12 =	{0x24,  10,   2, 0x0000, p_2};
static const cob_field_attr a_13 =	{0x10,   9,   2, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {50, (cob_u8_ptr)"==================================================", &a_1};
static const cob_field c_2	= {50, (cob_u8_ptr)"     SQLITE3 RELATIONAL DATABASE CONNECTIVITY     ", &a_1};
static const cob_field c_3	= {43, (cob_u8_ptr)"Database operations completed successfully.", &a_1};
static const cob_field c_4	= {52, (cob_u8_ptr)"[INFO] Connecting to SQLite database 'company.db'...", &a_1};
static const cob_field c_5	= {10, (cob_u8_ptr)"company.db", &a_1};
static const cob_field c_6	= {39, (cob_u8_ptr)"[ERROR] Could not open database. Code: ", &a_1};
static const cob_field c_7	= {30, (cob_u8_ptr)"[INFO] Connected successfully.", &a_1};
static const cob_field c_8	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_9	= {29, (cob_u8_ptr)"[INFO] Initializing schema...", &a_1};
static const cob_field c_10	= {93, (cob_u8_ptr)"CREATE TABLE IF NOT EXISTS employees (id INT PRIMARY KEY, name TEXT, dept TEXT, salary REAL);", &a_1};
static const cob_field c_11	= {31, (cob_u8_ptr)"[ERROR] Table creation failed: ", &a_1};
static const cob_field c_12	= {22, (cob_u8_ptr)"DELETE FROM employees;", &a_1};
static const cob_field c_13	= {32, (cob_u8_ptr)"[INFO] Schema ready and cleared.", &a_1};
static const cob_field c_14	= {36, (cob_u8_ptr)"[INFO] Inserting employee records...", &a_1};
static const cob_field c_15	= {77, (cob_u8_ptr)"INSERT INTO employees VALUES (101, 'Alice Jenkins', 'Engineering', 95000.00);", &a_1};
static const cob_field c_16	= {73, (cob_u8_ptr)"INSERT INTO employees VALUES (102, 'Bob Rodriguez', 'Finance', 82500.50);", &a_1};
static const cob_field c_17	= {74, (cob_u8_ptr)"INSERT INTO employees VALUES (103, 'Carol Smith', 'Operations', 71200.00);", &a_1};
static const cob_field c_18	= {74, (cob_u8_ptr)"INSERT INTO employees VALUES (104, 'David Kim', 'Engineering', 110000.00);", &a_1};
static const cob_field c_19	= {35, (cob_u8_ptr)"[INFO] 4 employee records inserted.", &a_1};
static const cob_field c_20	= {56, (cob_u8_ptr)"[INFO] Executing query: SELECT ordered by salary DESC...", &a_1};
static const cob_field c_21	= {64, (cob_u8_ptr)"----------------------------------------------------------------", &a_1};
static const cob_field c_22	= {64, (cob_u8_ptr)"ID   | NAME                 | DEPARTMENT      | SALARY          ", &a_1};
static const cob_field c_23	= {66, (cob_u8_ptr)"SELECT id, name, dept, salary FROM employees ORDER BY salary DESC;", &a_1};
static const cob_field c_24	= {34, (cob_u8_ptr)"[ERROR] Query preparation failed: ", &a_1};
static const cob_field c_25	= {1, (cob_u8_ptr)"0", &a_5};
static const cob_field c_26	= {1, (cob_u8_ptr)"1", &a_5};
static const cob_field c_27	= {2, (cob_u8_ptr)"20", &a_6};
static const cob_field c_28	= {1, (cob_u8_ptr)"2", &a_5};
static const cob_field c_29	= {2, (cob_u8_ptr)"15", &a_6};
static const cob_field c_30	= {1, (cob_u8_ptr)"3", &a_5};
static const cob_field c_31	= {3, (cob_u8_ptr)" | ", &a_1};
static const cob_field c_32	= {18, (cob_u8_ptr)"Total Employees : ", &a_1};
static const cob_field c_33	= {18, (cob_u8_ptr)"Total Payroll   : ", &a_1};
static const cob_field c_34	= {18, (cob_u8_ptr)"Average Salary  : ", &a_1};
static const cob_field c_35	= {33, (cob_u8_ptr)"[INFO] Closing SQLite database...", &a_1};
static const cob_field c_36	= {31, (cob_u8_ptr)"[INFO] Database closed cleanly.", &a_1};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


static COB_INLINE COB_A_INLINE int
cob_cmp_s32 (const void *p, const cob_s64_t n)
{
	int	val;
	void	*x;
	x = &val;
	optim_memcpy (x, p, 4);
	return (val < n) ? -1 : (val > n);
}

